# Только для локальной разработки.
# В prod запускай: docker compose -f docker-compose.yml up
services:
  db:
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    ports:
      - "127.0.0.1:6379:6379"

  rabbitmq:
    ports:
      - "127.0.0.1:5672:5672"

  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"

  kafka:
    ports:
      - "127.0.0.1:9092:9092"

  clickhouse:
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"

  backend:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app

  celery:
    volumes:
      - ./backend:/app

  beat:
    volumes:
      - ./backend:/app