# Generated by Django 5.0 on 2026-06-21 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='body_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=30)),
                ('apartment', models.CharField(blank=True, default='', max_length=30)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
