# Generated by Django 5.0 on 2026-06-21 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_body_params_user_notification_prefs_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_status', models.CharField(blank=True, choices=[('self_employed', 'Самозанятый'), ('ip', 'Индивидуальный предприниматель'), ('ooo', 'ООО')], max_length=20)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('bank_account', models.CharField(blank=True, max_length=20)),
                ('bank_bik', models.CharField(blank=True, max_length=9)),
                ('shop_description', models.TextField(blank=True)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('tariff', models.CharField(choices=[('free', 'Базовый (бесплатный)'), ('advanced', 'Расширенный')], default='free', max_length=20)),
                ('offer_accepted', models.BooleanField(default=False)),
                ('offer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('incomplete', 'Черновик'), ('active', 'Активен')], default='incomplete', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
