# Generated by Django 5.0 on 2026-06-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='shop_banner',
            field=models.ImageField(blank=True, null=True, upload_to='shops/banners/'),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
