# Generated by Django 5.0 on 2026-06-23 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_delivered_at(apps, schema_editor):
    """Существующие доставленные заказы не имели delivered_at (поля не было).
    Приближаем датой updated_at, чтобы у них работал отсчёт срока возврата (Ф23).
    Новые заказы получат точную дату в переходе shipped->delivered."""
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='delivered', delivered_at__isnull=True).update(
        delivered_at=models.F('updated_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_checkout_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_delivered_at, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Заявка подана'), ('approved', 'Одобрен'), ('received', 'Товар принят'), ('refunded', 'Деньги возвращены'), ('rejected', 'Отклонён'), ('disputed', 'Спор')], default='requested', max_length=20)),
                ('reason', models.CharField(choices=[('size', 'Не подошёл размер'), ('defect', 'Брак / дефект'), ('not_as_described', 'Не соответствует описанию'), ('changed_mind', 'Передумал'), ('other', 'Другое')], max_length=30)),
                ('reason_text', models.TextField(blank=True, default='')),
                ('method', models.CharField(choices=[('pickup', 'Пункт выдачи'), ('courier', 'Курьер')], default='pickup', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('resolution_comment', models.TextField(blank=True, default='')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('arbitrated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnrequest')),
            ],
        ),
    ]
