# Generated by Django 5.0 on 2026-06-23 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_brandfollow_sellerreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('editorial', 'Редакция'), ('brand', 'Бренд')], default='editorial', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='looks/')),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='looks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.look')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='look_items', to='products.product')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('look', 'product')},
            },
        ),
    ]
